### ISSUE TITLE
Mockups y plantilla UI

### ISSUE THREAD

**Issue by SebasGambaDev** [SebasGambaDev/SistemaBibliotecario#5]

**Comment by NicolasGom3z** [comment]
![image](https://user-images.githubusercontent.com/47665470/133868899-9f994dca-61f1-454b-b420-4277b3e69dac.png)

**Comment by NicolasGom3z** [comment]
![image](https://user-images.githubusercontent.com/47665470/133868956-f94eeaca-8e7f-4807-8c03-8027f5d18ee1.png)

**Comment by NicolasGom3z** [comment]
[Desktop - 2.pdf](https://github.com/SebasGambaDev/SistemaBibliotecario/files/7189120/Desktop.-.2.pdf)
[Desktop - 3.pdf](https://github.com/SebasGambaDev/SistemaBibliotecario/files/7189121/Desktop.-.3.pdf)
[Desktop - 1.pdf](https://github.com/SebasGambaDev/SistemaBibliotecario/files/7189122/Desktop.-.1.pdf)

**Comment by NicolasGom3z** [comment]
[Mockup.pdf](https://github.com/SebasGambaDev/SistemaBibliotecario/files/7240578/Mockup.pdf)
